name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.7.2]

    steps:
      - uses: actions/checkout@v2 # Clona el repositorio

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install # Instala las dependencias

      - run: npm test # Ejecuta las pruebas unitarias con Jest
